# Generated by Django 5.0.6 on 2026-04-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailysnapshot',
            new_name='daily_snaps_user_id_79b1ab_idx',
            old_name='snapshot_user_date_idx',
        ),
    ]
