# Generated by Django 5.0.6 on 2026-04-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='recommendat_user_id_c38ac1_idx',
            old_name='rec_user_status_time_idx',
        ),
    ]
