# Generated by Django 5.0.6 on 2026-04-24 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='behaviorevent',
            new_name='behavior_ev_user_id_547c10_idx',
            old_name='event_user_type_time_idx',
        ),
        migrations.RenameIndex(
            model_name='behaviorevent',
            new_name='behavior_ev_user_id_1f7ffc_idx',
            old_name='event_user_hour_day_idx',
        ),
        migrations.RenameIndex(
            model_name='habit',
            new_name='habits_user_id_bf7d30_idx',
            old_name='habit_user_active_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='habitlog',
            new_name='habit_logs_user_id_ba2612_idx',
            old_name='habitlog_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='habitlog',
            new_name='habit_logs_habit_i_885f2e_idx',
            old_name='habitlog_habit_date_idx',
        ),
        migrations.AddIndex(
            model_name='behaviorevent',
            index=models.Index(fields=['-occurred_at'], name='behavior_ev_occurre_87fddc_idx'),
        ),
    ]
