# Generated by Django 5.0.6 on 2026-04-24 06:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='goal',
            new_name='goals_user_id_62e177_idx',
            old_name='goal_user_status_time_idx',
        ),
        migrations.RenameIndex(
            model_name='goal',
            new_name='goals_user_id_86adfb_idx',
            old_name='goal_user_cat_status_idx',
        ),
        migrations.RenameIndex(
            model_name='goalactivity',
            new_name='goal_activi_goal_id_2d380f_idx',
            old_name='gact_goal_time_idx',
        ),
        migrations.RenameIndex(
            model_name='goalactivity',
            new_name='goal_activi_user_id_23ab8c_idx',
            old_name='gact_user_time_idx',
        ),
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goalactivity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goaltask',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
