# Generated by Django 5.0.6 on 2026-04-24 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_user_id_5029a0_idx',
            old_name='conv_user_arch_time_idx',
        ),
        migrations.RenameIndex(
            model_name='memoryembedding',
            new_name='memory_embe_user_id_e20a28_idx',
            old_name='memb_user_src_imp_idx',
        ),
        migrations.RenameIndex(
            model_name='memoryembedding',
            new_name='memory_embe_user_id_b9e7e0_idx',
            old_name='memb_user_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='memoryinsight',
            new_name='memory_insi_user_id_4b80ef_idx',
            old_name='insight_user_type_active_idx',
        ),
        migrations.AddIndex(
            model_name='memoryinsight',
            index=models.Index(fields=['user', '-confidence'], name='memory_insi_user_id_df310b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'),
        ),
    ]
